// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://glbczcppncnarlwrcmig.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdsYmN6Y3BwbmNuYXJsd3JjbWlnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwOTM0OTMsImV4cCI6MjA2ODY2OTQ5M30.FNLaHgCa4FC7GdYdRDVTO_dolA38AvBfKcylVA0K9nM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});